### ISSUE TITLE
Blank editor page -> Syntax highlight error -> Unexpected end of file -> Hover text shows repeated warnings for the same thing.

### ISSUE THREAD

**Issue by JohnRudden** [autostep/AutoStep.Editor#5] opened 2020-02-04 10:19 UTC
When everything is deleted from the editor page, a syntax highlight error is shown. The hover text  indicates 'Unexpected end of file' which is correct, however, the hover text also says 'No step definitions could be found that match this step.'

This text is repeated 6 times.

![HoverText](https://user-images.githubusercontent.com/52506030/73735851-cad5bd00-4737-11ea-9034-60aa566e40b4.PNG)

**Comment by alistairjevans** [comment] 2020-02-04 10:22
This might end up moving to the AutoStep repository, once I've figured out where the issue is. Could be related to the editor, but could also be a language issue.

**Closed as completed** 2020-04-10 14:36 UTC
Labels: bug
